# Generated by Django 5.2.7 on 2026-04-11 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('legal_indexing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prompt', models.TextField()),
                ('normalized_prompt', models.TextField(blank=True)),
                ('detected_matter', models.CharField(blank=True, max_length=64)),
                ('detected_topics_json', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=32)),
                ('final_answer', models.TextField(blank=True)),
                ('model_name', models.CharField(blank=True, max_length=120)),
                ('answer_metadata_json', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsultationRetrieval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.FloatField()),
                ('retrieval_type', models.CharField(choices=[('keyword', 'Keyword'), ('semantic', 'Semantic'), ('hybrid', 'Hybrid')], max_length=32)),
                ('rank', models.PositiveIntegerField(default=1)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retrievals', to='consultations.consultation')),
                ('fragment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_retrievals', to='legal_indexing.documentfragment')),
            ],
            options={
                'ordering': ['rank', 'id'],
                'unique_together': {('consultation', 'fragment')},
            },
        ),
    ]
