# Generated by Django 5.2.7 on 2026-04-11 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('legal_sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=100)),
                ('document_type', models.CharField(choices=[('law', 'Law'), ('regulation', 'Regulation'), ('thesis', 'Thesis'), ('precedent', 'Precedent'), ('criterion', 'Criterion')], default='law', max_length=32)),
                ('jurisdiction', models.CharField(default='federal', max_length=100)),
                ('subject_area', models.CharField(choices=[('labor_individual', 'Labor Individual'), ('social_security', 'Social Security'), ('occupational_risk', 'Occupational Risk'), ('general', 'General')], default='general', max_length=32)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('last_reform_date', models.DateField(blank=True, null=True)),
                ('version_label', models.CharField(blank=True, max_length=100)),
                ('official_url', models.URLField(blank=True)),
                ('raw_text', models.TextField()),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('is_current', models.BooleanField(default=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='legal_sources.source')),
            ],
            options={
                'ordering': ['title'],
                'unique_together': {('source', 'title', 'version_label')},
            },
        ),
    ]
