# Generated by Django 5.2.7 on 2026-04-11 14:30

import common.db_fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('legal_documents', '0001_initial'),
        ('legal_sources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentFragment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fragment_type', models.CharField(choices=[('article', 'Article'), ('fraction', 'Fraction'), ('chapter', 'Chapter'), ('thesis', 'Thesis'), ('rubro', 'Rubro'), ('precedent', 'Precedent'), ('section', 'Section')], max_length=32)),
                ('article_number', models.CharField(blank=True, max_length=32)),
                ('section_path', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('normalized_content', models.TextField(blank=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('order_index', models.PositiveIntegerField(default=1)),
                ('legal_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fragments', to='legal_documents.legaldocument')),
            ],
            options={
                'ordering': ['legal_document', 'order_index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DocumentEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('embedding', common.db_fields.VectorField(blank=True, null=True)),
                ('model_name', models.CharField(max_length=120)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('fragment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='legal_indexing.documentfragment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IngestionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_type', models.CharField(choices=[('ingestion', 'Ingestion'), ('indexing', 'Indexing')], max_length=32)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingestion_jobs', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='legal_sources.source')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FragmentTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confidence', models.FloatField(default=0.0)),
                ('fragment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_relations', to='legal_indexing.documentfragment')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fragment_relations', to='legal_indexing.legaltopic')),
            ],
        ),
        migrations.AddIndex(
            model_name='documentfragment',
            index=models.Index(fields=['fragment_type'], name='legal_index_fragmen_f42c6a_idx'),
        ),
        migrations.AddIndex(
            model_name='documentfragment',
            index=models.Index(fields=['article_number'], name='legal_index_article_ec1c48_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fragmenttopic',
            unique_together={('fragment', 'topic')},
        ),
    ]
