# Generated by Django 5.2.7 on 2026-04-11 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultations', '0001_initial'),
        ('legal_indexing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationCitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('citation_label', models.CharField(max_length=255)),
                ('snippet_used', models.TextField()),
                ('order_index', models.PositiveIntegerField(default=1)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='consultations.consultation')),
                ('fragment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_citations', to='legal_indexing.documentfragment')),
            ],
            options={
                'ordering': ['order_index', 'id'],
            },
        ),
    ]
